home:
    hero_image: "about_hero.jpg"
    hero_text: "<p>The Open Data Institute</p>"
    hero_link: "http://theodi.org/about"
    hero_alt: "Knowledge for everyone"
    links:
      -
        image: "20140113_odifutures_food.jpg"
        link: "http://theodi.org/research-afternoons/show-me-the-future-of-food-and-open-data"
        alt: "Show me the future of Open Data and... Food"
      -
        image: "20131220_odcs_education.jpg"
        link: "http://theodi.org/education-open-data-challenge-series"
        alt: "Open Data Challenge Series: Education"
      -
        frame: "/news/module"
      -
        image: "odc_modules.jpg"
        link: "https://certificates.theodi.org/"
        alt: "Open Data Certificates"
      -
        image: "annualreport_module.jpg"
        Alt: "ODI's 2nd Year: Annual Report"
        link: "/odis-second-year-annual-report"
      -
        image: "20140113_odifriday_opensteetmap.jpg"
        link: "http://theodi.org/lunchtime-lectures/friday-lunchtime-lecture-typhoon-crisis-mapping-with-openstreetmap"
        alt: "Latest Lunchtime Lecture: Typhoon Crisis Mapping with OpenStreetMap"
      -
        image: "node_module.jpg"
        link: "/nodes"
        alt: "ODI Nodes"
      -
        frame: "/blog/module"
      -
        frame: "/courses/module"
      - 
        frame: "/events/module"
      -
        image: "training&projects_module.jpg"
        link: "/learning"
        alt: "Training and projects"
      -
        title: Introducing Open Data Partnership for Development
        text: GLOBAL PROJECTS
        link: /odp4d
        colour: 2
about:
    title: "About"
    hero_image: "about_hero.jpg"
    alt: "Knowlege for Everyone"
    links:
     -
       image: "about_module.jpg"
       link: "/about-us"
       alt: "Who are we? What do we do?"
     -
       image: "annualreport_module.jpg"
       link: "/odis-first-year-annual-report"
       alt: "ODI Annual Report 2013"
     -
       image: "jobs_module.jpg"
       link: "/jobs"
       alt: "Jobs: Join the ODI"
     -
       image: "dataasculture_module1.jpg"
       link: "/culture"
       alt: "Data as culture"
     -
       image: "faq_module.jpg"
       link: "/faq"
       alt: "Frequently Asked Questions"
     -
       image: "people_module.jpg"
       link: "/team"
       alt: "ODI People"
     -
       image: "contactus_module.jpg"
       link: "/contact"
       alt: "Contact us"
     -
       image: "press_module.jpg"
       link: "/newsroom"
       alt: "Press - enquire within"
     -
       image: "procurement_modules.jpg"
       link: "/procurement"
       alt: "Procurement"
get-involved:
     title: "Get Involved"
     hero_image: "getinvolved_hero.jpg"
     alt: "Get involved"
     links:
      -
       image: "member_module.jpg"
       link: "/join-us"
       alt: "Join us - become an ODI member"
      -
       image: "node_module.jpg"
       link: "/nodes"
       alt: "ODI nodes"
      -
       image: "odcs_modules.jpg"
       link: "/challenge-series"
       alt: "Open Data Challenge Series"
      -
       image: "consultationresponses_modules.jpg"
       link: "/consultation-responses"
       alt: "Consultation Responses"
      -
       image: "startup_module.jpg"
       link: "/start-ups"
       alt: "Startups"
      -
       image: "certificates_module.jpg"
       link: "http://certificates.theodi.org"
       alt: "Open Data Certificates"
learning:
    title: "Learning"
    hero_image: "learn_hero.jpg"
    alt: "Learn"
    links:
     -
      image: "courses_modules.jpg"
      link: "/courses"
      alt: "Courses"
     -
      image: "casestudies_modules.jpg"
      link: "/case-studies"
      alt: "Case studies"
     -
      image: "fridaylunchtimelectures_module.jpg"
      link: "/lunchtime-lectures"
      alt: "Friday Lunchtime Lectures"
     -
      image: "guides_modules.jpg"
      link: "/guides"
      alt: "Guides"
